export const UPDATE_INPUT = "UPDATE_INPUT";
export const SEARCH_DOI = "SEARCH_DOI"
export const UPDATE_CITATION = "UPDATE_CITATION"
export const UPDATE_STATUS = "UPDATE_STATUS"
export const MAKE_DOI_OBJ = "MAKE_DOI_OBJ"
export const ADD_WORKS_CITED = "ADD_WORKS_CITED"
export const UPDATE_FORMAT = "UPDATE_FORMAT"